spring:
  application:
    name: projeto-spring-lol
  datasource:
    url: jdbc:h2:mem:apilol
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true